name: my_website
description: Eng / Ibrahim Medhat Professional Website Get one yourself.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.2+4

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  # Responsiveness
  flutter_screenutil: ^5.0.0+2
  intl_phone_field: ^3.2.0
  device_preview:
  device_apps:
  # Firebase
  firebase_core:
  # Linking
  url_launcher:
  # State Management
  get_it:
  flutter_bloc:
  # Addictiveness
  cupertino_icons: ^1.0.2
  # Asset management
  flutter_svg:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  # assets manager
  build_runner:
  flutter_gen_runner:
  flutter_launcher_icons:


#asset generator
flutter_gen:
  output: lib/src/core/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/service_images/
    - assets/contact_icons/

