name: my_website
description: Eng / Ibrahim Medhat Professional Website Get one yourself.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.2+4

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  device_preview:
  firebase_core:
  url_launcher:
  vector_math:
  flutter_bloc:
  device_apps:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/service_images/
    - assets/contact_icons/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic