// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMZgIuLGFLzZok9apza1b_K98vfjzNNQs',
    appId: '1:594189205385:web:d92570237f106b459aeb58',
    messagingSenderId: '594189205385',
    projectId: 'ibrahim-website-1',
    authDomain: 'ibrahim-website-1.firebaseapp.com',
    storageBucket: 'ibrahim-website-1.appspot.com',
    measurementId: 'G-0ZTHYYZ90D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYeQ1csXB8Pv8V-kgN5l5XsGzXVItdolk',
    appId: '1:594189205385:android:272c561dff68e5189aeb58',
    messagingSenderId: '594189205385',
    projectId: 'ibrahim-website-1',
    storageBucket: 'ibrahim-website-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeG8lucRL7RON9MatAyi0G3MX1q3NQds4',
    appId: '1:594189205385:ios:a3e2485700651afb9aeb58',
    messagingSenderId: '594189205385',
    projectId: 'ibrahim-website-1',
    storageBucket: 'ibrahim-website-1.appspot.com',
    iosClientId: '594189205385-s1q13v4f98n9s6095b7nn74ka4u066nr.apps.googleusercontent.com',
    iosBundleId: 'com.example.myWebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeG8lucRL7RON9MatAyi0G3MX1q3NQds4',
    appId: '1:594189205385:ios:b79a52b3a38ce79b9aeb58',
    messagingSenderId: '594189205385',
    projectId: 'ibrahim-website-1',
    storageBucket: 'ibrahim-website-1.appspot.com',
    iosClientId: '594189205385-6llvqiasbsqksqjr40gub7au8ovadlb7.apps.googleusercontent.com',
    iosBundleId: 'com.example.myWebsite.RunnerTests',
  );
}
