// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_H0yquUyWjyZ8MT1IgelNGFRhP6EkkU0',
    appId: '1:159161524183:web:dd6f12024feba2d7dbf592',
    messagingSenderId: '159161524183',
    projectId: 'ibrahim-medhat',
    authDomain: 'ibrahim-medhat.firebaseapp.com',
    storageBucket: 'ibrahim-medhat.appspot.com',
    measurementId: 'G-RVXJE93JLT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxQw1sUvSospkug1giJMhAVnnGbcPDwjU',
    appId: '1:159161524183:android:4f7c530290a85950dbf592',
    messagingSenderId: '159161524183',
    projectId: 'ibrahim-medhat',
    storageBucket: 'ibrahim-medhat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIysIGtIV8TnsDOQ_gJO9V-IPQ7I-XwvY',
    appId: '1:159161524183:ios:4136abd10b45a60cdbf592',
    messagingSenderId: '159161524183',
    projectId: 'ibrahim-medhat',
    storageBucket: 'ibrahim-medhat.appspot.com',
    iosClientId: '159161524183-fjupviqqsiu5fu01lgi9ao9i3d6pijle.apps.googleusercontent.com',
    iosBundleId: 'com.example.myWebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIysIGtIV8TnsDOQ_gJO9V-IPQ7I-XwvY',
    appId: '1:159161524183:ios:0790a77b3e2c9dacdbf592',
    messagingSenderId: '159161524183',
    projectId: 'ibrahim-medhat',
    storageBucket: 'ibrahim-medhat.appspot.com',
    iosClientId: '159161524183-bagg3coj6bn3d17ghlqcuchpoaopd3dg.apps.googleusercontent.com',
    iosBundleId: 'com.example.myWebsite.RunnerTests',
  );
}
